# Generated by Django 5.1.4 on 2026-07-18 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_add_catalog_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('closed', 'Yopilgan'), ('archived', 'Arxiv')], db_index=True, default='draft', max_length=20)),
                ('audience', models.CharField(choices=[('students', 'Talabalar'), ('staff', "Xodimlar / o'qituvchilar"), ('all', 'Hammasi')], default='all', max_length=20, verbose_name='Auditoriya')),
                ('privacy_mode', models.CharField(choices=[('open', "Ochiq (javob ↔ shaxs bog'lanadi)"), ('anonymous', 'Anonim (ishtirok ochiq, javob unlink)')], default='anonymous', help_text="Publish dan keyin o'zgarmaydi", max_length=20, verbose_name='Maxfiylik rejimi')),
                ('stats_level', models.CharField(choices=[('none', 'Faqat umumiy'), ('coarse', 'Fakultet + kurs'), ('detailed', "Yo'nalishgacha")], default='coarse', max_length=20, verbose_name='Statistika darajasi')),
                ('min_n_for_breakdown', models.PositiveSmallIntegerField(default=10, verbose_name='Kesim uchun minimal n (k-anonymity)')),
                ('store_group_meta', models.BooleanField(default=False, verbose_name="Guruh meta (anonimda default o'chiq)")),
                ('track_participation', models.BooleanField(default=True, verbose_name='Ishtirokni kuzatish (kim topshirgan)')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash')),
                ('study_years', models.JSONField(blank=True, default=list, help_text="Masalan [1,2,3]. Bo'sh = barcha kurslar", verbose_name='Kurslar')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='surveys/qr/%Y/%m/', verbose_name='QR kod')),
                ('public_path', models.CharField(blank=True, help_text="/s/{uuid} — frontend yo'li", max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
                ('faculties', models.ManyToManyField(blank=True, related_name='surveys', to='core.faculty', verbose_name='Fakultetlar')),
                ('groups', models.ManyToManyField(blank=True, related_name='surveys', to='core.studygroup', verbose_name='Guruhlar')),
                ('specialties', models.ManyToManyField(blank=True, related_name='surveys', to='core.specialty', verbose_name="Yo'nalishlar")),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.university', verbose_name='Universitet')),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Boshlangan'), ('submitted', 'Topshirilgan')], db_index=True, default='started', max_length=20)),
                ('token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_used', models.BooleanField(default=False)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_day', models.DateField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ishtirok',
                'verbose_name_plural': 'Ishtiroklar',
                'db_table': 'survey_participations',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('q_type', models.CharField(choices=[('single', 'Bir tanlov'), ('multiple', "Ko'p tanlov"), ('text', 'Yozma (qisqa)'), ('textarea', 'Yozma (batafsil)'), ('rating', 'Yulduz'), ('nps', 'NPS (0–10)'), ('likert', 'Likert shkala')], max_length=20)),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'db_table': 'survey_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='{"faculty_id": "...", "study_year": 2} — guruh default yo\'q')),
                ('answers_encrypted', models.TextField(verbose_name='Shifrlangan javoblar')),
                ('content_hash', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('signature', models.CharField(max_length=64, verbose_name='HMAC imzo')),
                ('is_sealed', models.BooleanField(default=True)),
                ('seal_version', models.PositiveSmallIntegerField(default=1)),
                ('submitted_bucket', models.DateTimeField(db_index=True, help_text='Soat boshiga yaxlitlangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'db_table': 'survey_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status', 'start_at', 'end_at'], name='surveys_status_524549_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['privacy_mode', 'status'], name='surveys_privacy_a88c84_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyparticipation',
            index=models.Index(fields=['survey', 'status'], name='survey_part_survey__2cd716_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyparticipation',
            constraint=models.UniqueConstraint(fields=('survey', 'user'), name='uniq_survey_participation_user'),
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['survey', 'order'], name='survey_ques_survey__74e9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey', 'submitted_bucket'], name='survey_resp_survey__e9faa7_idx'),
        ),
    ]
