# Generated by Django 5.1.4 on 2026-03-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_hemis_i_30914b_idx',
            old_name='users_hemis_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_role_0ace22_idx',
            old_name='users_role_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_univers_6cfd8d_idx',
            old_name='users_uni_fac_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_group_i_d3ba74_idx',
            old_name='users_group_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='academic_degree',
            field=models.CharField(blank=True, help_text='Masalan: Fan nomzodi, Fan doktori', max_length=100, verbose_name='Akademik daraja'),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_rank',
            field=models.CharField(blank=True, help_text='Masalan: Dotsent, Professor', max_length=100, verbose_name='Akademik unvon'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, help_text='HEMIS dan olingan rasm manzili', max_length=500, verbose_name='Profil rasmi URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text="staffPosition.name — masalan: Katta o'qituvchi", max_length=200, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_hemis_sync',
            field=models.DateTimeField(blank=True, help_text="HEMIS dan oxirgi marta ma'lumotlar yangilangan vaqt", null=True, verbose_name='Oxirgi HEMIS sinxronlash'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='SMS xabarnomalar uchun. Format: +998901234567', max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='study_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text="1, 2, 3, 4 — o'qish yili (talabalar uchun)", null=True, verbose_name="O'qish kursi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
