# Generated by Django 5.1.4 on 2026-07-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_picture_position_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], help_text="HEMIS orqali kelmaydi — qo'lda to'ldiriladi", max_length=1, null=True, verbose_name='Jinsi'),
        ),
    ]
