# Generated by Django 5.1.4 on 2026-07-18 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('login_ok', 'Login (muvaffaqiyatli)'), ('login_fail', 'Login (muvaffaqiyatsiz)'), ('logout', 'Chiqish'), ('user_create', 'Foydalanuvchi yaratildi'), ('user_update', 'Foydalanuvchi yangilandi'), ('user_deactivate', 'Foydalanuvchi bloklandi'), ('user_activate', 'Foydalanuvchi faollashtirildi'), ('role_change', "Rol o'zgartirildi"), ('pwd_reset', 'Parol tiklash'), ('hemis_sync', 'HEMIS sinxronlash')], db_index=True, max_length=30)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
