# Generated by Django 5.1.4 on 2026-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subject',
            new_name='subjects_hemis_c_1004ee_idx',
            old_name='subjects_hemis_idx',
        ),
        migrations.AlterField(
            model_name='specialty',
            name='hemis_specialty_id',
            field=models.CharField(blank=True, help_text="HEMIS tizimidagi yo'nalish identifikatori", max_length=50, verbose_name='HEMIS ID'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Guruh nomi'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='study_year',
            field=models.PositiveSmallIntegerField(help_text='1-kurs, 2-kurs, ...', verbose_name="O'qish kursi"),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='Kredit soati — KPI hisobi uchun', verbose_name='Kredit soati'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='hemis_course_id',
            field=models.CharField(blank=True, help_text='HEMIS tizimidagi kurs identifikatori', max_length=50, verbose_name='HEMIS kurs ID'),
        ),
        migrations.AlterField(
            model_name='university',
            name='domain',
            field=models.CharField(blank=True, help_text='HEMIS SSO uchun domen, masalan: tashpi.uz', max_length=100, verbose_name='Domen'),
        ),
    ]
