# Generated by Django 5.1.4 on 2026-05-24 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hemis_sync_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemissynclog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
