# Generated by Django 5.1.4 on 2026-06-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hemissynclog_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['faculty', 'is_active'], name='specialties_faculty_b01e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['is_active', 'name'], name='specialties_is_acti_4147b6_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['specialty', 'is_active'], name='study_group_special_f46397_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['is_active', 'study_year', 'name'], name='study_group_is_acti_be52fc_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['faculty', 'is_active'], name='subjects_faculty_0a49ae_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active', 'name'], name='subjects_is_acti_dc7d22_idx'),
        ),
    ]
