# Generated by Django 5.1.4 on 2026-07-19 11:23

import apps.office.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.office.models.person_photo_path, verbose_name='Surat')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name="Bo'lim / fakultet")),
                ('academic_title', models.CharField(blank=True, max_length=150, verbose_name='Ilmiy unvon')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('office_room', models.CharField(blank=True, max_length=80, verbose_name='Kabinet')),
                ('reception_hours', models.CharField(blank=True, max_length=200, verbose_name='Qabul soatlari')),
                ('biography', models.TextField(blank=True, verbose_name='Qisqa biografiya')),
                ('responsibilities', models.TextField(blank=True, verbose_name="Vazifalar / mas'uliyat")),
                ('extra_info', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_public', models.BooleanField(default=True, verbose_name="Foydalanuvchilarga ko'rsatish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Mas'ul shaxs",
                'verbose_name_plural': "Mas'ul shaxslar",
                'db_table': 'office_responsible_persons',
                'ordering': ['order', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=300, verbose_name='Mavzu')),
                ('body', models.TextField(verbose_name='Murojaat matni')),
                ('category', models.CharField(choices=[('general', 'Umumiy'), ('academic', "O'quv jarayoni"), ('social', 'Ijtimoiy'), ('technical', 'Texnik'), ('complaint', 'Shikoyat'), ('suggestion', 'Taklif'), ('other', 'Boshqa')], default='general', max_length=30, verbose_name='Kategoriya')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', "Ko'rib chiqilmoqda"), ('answered', 'Javob berilgan'), ('closed', 'Yopilgan')], db_index=True, default='pending', max_length=20)),
                ('answer_text', models.TextField(blank=True, verbose_name='Javob matni')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_late', models.BooleanField(default=False, verbose_name='Kechikib javob')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ichki izoh (admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_appeals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'db_table': 'office_appeals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.office.models.appeal_file_path, verbose_name='Fayl')),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='office.appeal')),
            ],
            options={
                'db_table': 'office_appeal_attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['status', 'created_at'], name='office_appe_status_85d96d_idx'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['user', 'created_at'], name='office_appe_user_id_6437c9_idx'),
        ),
    ]
