# Generated by Django 5.1.4 on 2026-07-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealattachment',
            name='kind',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Admin javobi')], db_index=True, default='user', max_length=10, verbose_name='Turi'),
        ),
    ]
